"""
    VacuumInput

Struct holding plasma boundary and mode data as provided from ForceFreeStates namelist and computed quantities.
For an axisymmetric boundary, nzeta_in = 1 and only the x and z arrays need to be provided - the code can then
be run with nzeta = 1 for 2D vacuum calculation or nzeta > 1 for 3D vacuum calculation. For a non-axisymmetric boundary,
nzeta_in > 1 and the x, y, and z arrays need to be provided - the code can then be run with nzeta = 1 for 2D vacuum calculation or
nzeta > 1 for 3D vacuum calculation. The arrays should be for a single field period only, with excluded endpoints.

# Fields

  - `x::Vector{Float64}`: Plasma boundary X-coordinate (length mtheta_in * nzeta_in)
  - `y::Vector{Float64}`: Plasma boundary Y-coordinate (length mtheta_in * nzeta_in)
  - `z::Vector{Float64}`: Plasma boundary Z-coordinate (length mtheta_in * nzeta_in)
  - `ν::Vector{Float64}`: Free parameter in specifying toroidal angle, ζ = ϕ + ν(θ), on input theta grid (axisymmetric only, length mtheta_in)
  - `mtheta_in::Int`: Number of input poloidal grid points
  - `nzeta_in::Int`: Number of input toroidal grid points (1 for axisymmetric, > 1 for non-axisymmetric)
  - `m_modes::Vector{Int}`: Vector of poloidal mode numbers. E.g. `collect(mlow:mhigh)` for a contiguous range.
  - `n_modes::Vector{Int}`: Vector of toroidal mode numbers. E.g. `collect(nlow:nhigh)` for a contiguous range or `collect(nlow:n_stride:nhigh)` for a strided list for stellarator mode-family calculations.
  - `mtheta::Int`: Number of vacuum calculation poloidal grid points
  - `nzeta::Int`: Number of vacuum calculation toroidal grid points (1 for 2D vacuum calculation, > 1 for 3D vacuum calculation)
  - `nfp::Int`: Number of field periods
"""
@kwdef struct VacuumInput
    x::Vector{Float64} = Float64[]
    y::Vector{Float64} = Float64[]
    z::Vector{Float64} = Float64[]
    ν::Vector{Float64} = Float64[]
    mtheta_in::Int = 0
    nzeta_in::Int = 1
    m_modes::Vector{Int} = [1]
    n_modes::Vector{Int} = [1]
    mtheta::Int = 1
    nzeta::Int = 1
    nfp::Int = 1
end

"""
    VacuumInput(
        equil::Equilibrium.PlasmaEquilibrium,
        ψ::Float64,
        mtheta::Int,
        nzeta::Int,
        m_modes::AbstractVector{<:Integer},
        n_modes::AbstractVector{<:Integer};
    ) -> VacuumInput

Constructor to create a VacuumInput struct for computing Green's functions at arbitrary flux surface.
Extracts plasma geometry from equilibrium at the given flux surface and packages it into VacuumInput format.

## Arguments

  - `equil`: Equilibrium solution
  - `ψ`: Normalized flux coordinate
  - `mtheta`: Number of vacuum calculation poloidal points
  - `nzeta`: Number of vacuum calculation toroidal points (1 for 2D, >1 for 3D)
  - `m_modes`: Poloidal mode numbers (e.g. `mlow:mhigh`)
  - `n_modes`: Toroidal mode numbers (e.g. `[n]` for a single mode, or `nlow:nhigh`)

## Returns

VacuumInput structure ready for compute_vacuum_response()
"""
function VacuumInput(
    equil::Equilibrium.PlasmaEquilibrium,
    ψ::Float64,
    mtheta::Int,
    nzeta::Int,
    m_modes::AbstractVector{<:Integer},
    n_modes::AbstractVector{<:Integer}
)
    # Extract plasma surface geometry at this psi
    r, z, ν = extract_plasma_surface_at_psi(equil, ψ)

    # Remove the last point to go from the [0, 2π] grid to VACUUM's [0, 2π) grid
    # and reverse the arrays for VACUUM's CW θ direction (θ_VAC = -θ_GPEC). This handedness is why
    # operators returned to GPEC (e.g. the surface-inductance current matrix) are conjugated.
    return VacuumInput(;
        x=reverse(r)[1:(end-1)],
        z=reverse(z)[1:(end-1)],
        ν=reverse(ν)[1:(end-1)],
        mtheta_in=length(r)-1,
        m_modes=collect(Int, m_modes),
        n_modes=collect(Int, n_modes),
        mtheta=mtheta,
        nzeta=nzeta
    )
end

"""
    expand_field_periods(inputs::VacuumInput) -> VacuumInput

Reconstruct the full-torus boundary from a single field period using the device field
periodicity. When `inputs.nfp > 1` (and the boundary is 3D), the input `x, y, z` arrays
describe one field period spanning ζ ∈ [0, 2π/nfp) on an `mtheta_in × nzeta_in` grid; the
full torus is generated by `nfp` rigid rotations about the Z-axis by 2π·k/nfp. The toroidal
counts `nzeta_in` and `nzeta` are scaled to their full-torus totals and `nfp` is reset to 1,
so all downstream code operates on the full surface unchanged.

This is the layer-1 interface: it shrinks the Python→Julia payload to one field period while
producing a full-torus geometry identical (to floating-point) to sending the whole torus.

Returns `inputs` unchanged for axisymmetric (`nzeta_in == 1`) or single-period (`nfp <= 1`) cases.
"""
function expand_field_periods(inputs::VacuumInput)
    (inputs.nfp <= 1 || inputs.nzeta_in <= 1) && return inputs

    nfp = inputs.nfp
    mt = inputs.mtheta_in
    nz = inputs.nzeta_in   # points per field period
    npts = mt * nz
    @assert length(inputs.x) == length(inputs.y) == length(inputs.z) == npts "per-period x, y, z must have length mtheta_in * nzeta_in"

    nz_full = nz * nfp
    xf = Vector{Float64}(undef, mt * nz_full)
    yf = similar(xf)
    zf = similar(xf)

    # Tile to full torus: period k is the single period rotated by α = 2π·k/nfp about Z.
    for k in 0:(nfp-1)
        α = 2π * k / nfp
        ca, sa = cos(α), sin(α)
        @inbounds for j in 1:nz, i in 1:mt
            src = i + mt * (j - 1)
            dst = i + mt * (j - 1 + k * nz)
            xf[dst] = inputs.x[src] * ca - inputs.y[src] * sa
            yf[dst] = inputs.x[src] * sa + inputs.y[src] * ca
            zf[dst] = inputs.z[src]
        end
    end

    return VacuumInput(;
        x=xf,
        y=yf,
        z=zf,
        ν=inputs.ν,
        mtheta_in=mt,
        nzeta_in=nz_full,
        m_modes=inputs.m_modes,
        n_modes=inputs.n_modes,
        mtheta=inputs.mtheta,
        nzeta=inputs.nzeta * nfp,
        nfp=1
    )
end

"""
    VacuumResponse

Output of [`compute_vacuum_response`](@ref): the vacuum energy matrix and the surface data the
boundary-integral solve produces along the way.

## Fields

  - `wv::Matrix{ComplexF64}`: Vacuum energy matrix Wᵛ (`num_modes × num_modes`), block-diagonal in n for 2D
  - `I_v::Matrix{ComplexF64}`: Vacuum surface-current matrix Iᵛ (`num_modes × num_modes`), left zeroed
    unless `compute_vacuum_response` is called with `compute_Iv=true`. Stored without the
    `μ₀`/`4π²` normalization: the physical surface inductance is `μ₀(2π)²·I_v⁻¹`
    (see `PerturbedEquilibrium.calc_surface_inductance`).
  - `plasma_pts`, `wall_pts::Matrix{Float64}`: Cartesian surface coordinates (`num_points × 3`)
"""
struct VacuumResponse
    wv::Matrix{ComplexF64}
    I_v::Matrix{ComplexF64}
    plasma_pts::Matrix{Float64}
    wall_pts::Matrix{Float64}
end

"""
    VacuumResponse(inputs::VacuumInput) -> VacuumResponse

Allocate zeroed output arrays sized for `inputs` (full torus, so `nfp` field periods).
"""
function VacuumResponse(inputs::VacuumInput)
    num_points = inputs.mtheta * inputs.nzeta * inputs.nfp
    num_modes = length(inputs.m_modes) * length(inputs.n_modes)
    return VacuumResponse(
        zeros(ComplexF64, num_modes, num_modes),
        zeros(ComplexF64, num_modes, num_modes),
        zeros(num_points, 3),
        zeros(num_points, 3)
    )
end

"""
    WallShapeSettings

Struct containing input settings for vacuum wall geometry.

# Fields

  - `shape::String`: String selecting wall shape. Options are:

        + `"nowall"`: No wall
        + `"conformal"`: Wall conformal to plasma surface at distance `a`
        + `"elliptical"`: Elliptical wall
        + `"dee"`: Dee-shaped wall
        + `"mod_dee"`: Modified Dee-shaped wall
        + `"filepath"`: Custom wall shape from the file you specify

    A non-axisymmetric boundary (`nzeta_in > 1`) supports `"nowall"` and `"conformal"`; the others
    are poloidal contours that get revolved and so need `nzeta_in == 1`.

  - `a::Float64`: Distance of wall from plasma in units of major radius (conformal), or shape parameter (others)

  - `aw::Float64`: Half-thickness parameter for Dee-shaped walls

  - `bw::Float64`: Elongation parameter for wall shapes

  - `cw::Float64`: Offset of the center of the wall from the major radius

  - `dw::Float64`: Triangularity parameter for wall shapes

  - `tw::Float64`: Sharpness of the corners of the wall (try 0.05 as initial value)

    # Core shape selection

  - `equal_arc_wall::Bool`: Flag to enforce equal arc length distribution of nodes on the wall
    (recommended unless wall is very close to plasma). Re-parameterizing the contour breaks the
    plasma/wall grid index correspondence that the singular quadrature relies on; it is ignored
    outright for `nzeta_in > 1` walls.
"""
@kwdef struct WallShapeSettings

    # Core shape selection
    shape::String = "nowall"

    # Standard geometric parameters for Dee/Mod-Dee
    a::Float64 = 0.3
    aw::Float64 = 0.05
    bw::Float64 = 1.5
    cw::Float64 = 0.0
    dw::Float64 = 0.5
    tw::Float64 = 0.05

    # Algorithmic options
    equal_arc_wall::Bool = true
end

"""
    PlasmaGeometry

Struct holding plasma geometry data on the mtheta grid for vacuum calculations. Arrays are
of length `mtheta`, where `mtheta` is the number of poloidal grid points and θ ∈ [0, 1).

# Fields

  - `x::Vector{Float64}`: Plasma surface R-coordinate on VACUUM theta grid
  - `z::Vector{Float64}`: Plasma surface Z-coordinate on VACUUM theta grid
  - `ν::Vector{Float64}`: Magnetic toroidal angle offset from geometric toroidal angle
"""
struct PlasmaGeometry
    x::Vector{Float64}
    z::Vector{Float64}
    ν::Vector{Float64}
end

"""
    WallGeometry

Struct holding wall geometry data for vacuum calculations. Arrays are of length
`mtheta`, where `mtheta` is the number of poloidal grid points and θ ∈ [0, 1).

# Fields

  - `nowall::Bool`: Boolean flag indicating if there is no wall
  - `x::Vector{Float64}`: Wall R-coordinates
  - `z::Vector{Float64}`: Wall Z-coordinates
"""
struct WallGeometry
    nowall::Bool
    x::Vector{Float64}
    z::Vector{Float64}
end

"""
    PlasmaGeometry(inputs::VacuumInput) -> PlasmaGeometry

Initialize the plasma surface geometry based on the provided vacuum inputs.
We interpolate the input plasma boundary arrays from the inputs struct onto the mtheta grid.

# Arguments

  - `inputs::VacuumInput`: Struct containing plasma boundary data

# Returns

  - `PlasmaGeometry`: Struct containing plasma surface coordinates, derivatives, and basis functions
"""
function PlasmaGeometry(inputs::VacuumInput)

    @assert !isempty(inputs.ν) "ν must be specified for 2D calculations"
    @assert length(inputs.x) == length(inputs.z) == length(inputs.ν) "x, z, and ν must have the same length"

    # Interpolate arrays from input onto mtheta grid
    θ_in = range(; start=0, length=inputs.mtheta_in, step=2π/inputs.mtheta_in)
    θ_out = range(; start=0, length=inputs.mtheta, step=2π/inputs.mtheta)

    # Use one-shot API with PeriodicBC
    x = cubic_interp(θ_in, inputs.x, θ_out; bc=PeriodicBC(; endpoint=:exclusive))
    z = cubic_interp(θ_in, inputs.z, θ_out; bc=PeriodicBC(; endpoint=:exclusive))
    ν = cubic_interp(θ_in, inputs.ν, θ_out; bc=PeriodicBC(; endpoint=:exclusive))

    return PlasmaGeometry(x, z, ν)
end

"""
    PlasmaGeometry3D

3D toroidal surface geometry for vacuum boundary integral calculations.

Built by toroidally extruding a 2D poloidal contour (`PlasmaGeometry`) and computing
Cartesian coordinates, tangent vectors, normals, and differential area elements.

# Fields

  - `mtheta::Int`: Number of poloidal grid points
  - `nzeta::Int`: Number of toroidal grid points
  - `r::Matrix{Float64}`: Surface points in Cartesian (X,Y,Z), shape (num_points, 3)
  - `dr_dθ::Matrix{Float64}`: Poloidal tangent vector ∂r/∂θ × dθ, shape (num_gridpoints, 3)
  - `dr_dζ::Matrix{Float64}`: Toroidal tangent vector ∂r/∂ζ × dζ, shape (num_points, 3)
  - `normal::Matrix{Float64}`: Oriented normal vectors, shape (num_points, 3)
  - `normal_orient::Int`: Forces normals to face out from vacuum region (+1 or -1)
"""
struct PlasmaGeometry3D
    mtheta::Int
    nzeta::Int
    r::Matrix{Float64}
    dr_dθ::Matrix{Float64}
    dr_dζ::Matrix{Float64}
    normal::Matrix{Float64}
    normal_orient::Int
end

"""
    PlasmaGeometry3D(inputs::VacuumInput)

Construct a 3D toroidal plasma surface from vacuum input data.

This constructor builds a `PlasmaGeometry3D` directly from the `VacuumInput`
struct, handling both axisymmetric (2D boundary, `nzeta_in == 1`) and fully
3D input boundaries (`nzeta_in > 1`).

## Axisymmetric input (inputs.nzeta_in == 1)

 1. Build a 2D poloidal contour on the vacuum `mtheta` grid using
    `PlasmaGeometry(inputs)` to obtain R(theta), Z(theta), and nu(theta).
 2. Toroidally extrude this contour onto a uniform `nzeta` grid using the
    SFL angle zeta = phi - nu(theta) and map to Cartesian coordinates:
    X = R(theta) * cos(zeta - nu(theta)),
    Y = R(theta) * sin(zeta - nu(theta)),
    Z = Z(theta).

## Fully 3D input (inputs.nzeta_in > 1)

 1. Interpolate the input (x, y, z) arrays from the original
    mtheta_in × nzeta_in grid onto the vacuum mtheta × nzeta grid using
    periodic bicubic interpolation in both angles. The inputs are assumed
    to already be equally spaced on the SFL angle grid.

## Steps

 1. Fit periodic bicubic splines to each Cartesian component on the
    (theta, zeta) grid.
 2. Compute tangent vectors dr/dtheta and dr/dzeta from spline derivatives,
    scaled by the grid spacings.
 3. Form oriented normals via the cross product
    n = (dr/dtheta) × (dr/dzeta) and enforce a consistent orientation
    (inward for the plasma surface).
 4. Compute average poloidal/toroidal grid spacings and report the
    aspect ratio for diagnostics.

## Arguments

  - `inputs::VacuumInput`: Vacuum calculation inputs defining the boundary
    geometry and the desired `mtheta, nzeta` resolution.

## Returns

  - `PlasmaGeometry3D`: Complete 3D surface description on the
    `mtheta × nzeta` grid, including points, tangents, normals, and
    orientation.
"""
function PlasmaGeometry3D(inputs::VacuumInput)

    # Extract 2D poloidal data
    (; mtheta, nzeta) = inputs
    num_points = mtheta * nzeta
    dθ = 2π / mtheta
    dζ = 2π / nzeta
    θ_grid = range(; start=0, length=mtheta, step=dθ)
    ζ_grid = range(; start=0, length=nzeta, step=dζ)

    # Allocate output arrays
    r = zeros(num_points, 3)
    dr_dθ = zeros(num_points, 3)
    dr_dζ = zeros(num_points, 3)
    normal = zeros(num_points, 3)

    if inputs.nzeta_in == 1
        # Build 3D surface point-by-point from 2D contour
        surf_2D = PlasmaGeometry(inputs)
        for i in 1:mtheta, (j, ζ) in enumerate(ζ_grid)
            # Our 3D grids are the SFL angle ζ = ϕ - ν
            r[i+mtheta*(j-1), 1] = surf_2D.x[i] * cos(ζ - surf_2D.ν[i])
            r[i+mtheta*(j-1), 2] = surf_2D.x[i] * sin(ζ - surf_2D.ν[i])
            r[i+mtheta*(j-1), 3] = surf_2D.z[i]
        end
    else
        # Interpolate 3D inputs onto vacuum grid
        @assert !isempty(inputs.y) "y must be provided for 3D (nzeta_in > 1) inputs"
        @assert length(inputs.x) == length(inputs.y) == length(inputs.z) == inputs.mtheta_in * inputs.nzeta_in "x, y, z must have length mtheta_in * nzeta_in"
        θ_in = range(; start=0, length=inputs.mtheta_in, step=2π/inputs.mtheta_in)
        ζ_in = range(; start=0, length=inputs.nzeta_in, step=2π/inputs.nzeta_in)
        θ_flat = repeat(collect(θ_grid), nzeta)
        ζ_flat = repeat(collect(ζ_grid); inner=mtheta)
        grid_points = (θ_flat, ζ_flat)
        for (k, data) in enumerate((inputs.x, inputs.y, inputs.z))
            itp = cubic_interp((θ_in, ζ_in), reshape(data, inputs.mtheta_in, inputs.nzeta_in); bc=(PeriodicBC(; endpoint=:exclusive), PeriodicBC(; endpoint=:exclusive)))
            r[:, k] = itp(grid_points)
        end
    end

    # Compute tangent vectors and normal vectors via periodic bicubic splines
    itps = [cubic_interp((θ_grid, ζ_grid), reshape(r[:, k], mtheta, nzeta); bc=(PeriodicBC(; endpoint=:exclusive), PeriodicBC(; endpoint=:exclusive))) for k in 1:3]
    for i in 1:mtheta, j in 1:nzeta
        idx = i + (j - 1) * mtheta
        for k in 1:3
            partials = itps[k].nodal_derivs.partials
            dr_dθ[idx, k] = partials[2, i, j]
            dr_dζ[idx, k] = partials[3, i, j]
        end
        cross3!(normal, dr_dθ, dr_dζ, idx)
    end

    # Determine normal orientation (inward for plasma) and enforce it
    idx = argmax(view(r, :, 1)) # outboard midplane
    normal_orient = normal[idx, 1] < 0 ? 1 : -1
    normal .*= normal_orient

    # Warn if grid spacing is highly anisotropic
    spacing_θ = sqrt(sum(abs2, dr_dθ) / size(dr_dθ, 1)) * dθ
    spacing_ζ = sqrt(sum(abs2, dr_dζ) / size(dr_dζ, 1)) * dζ
    aspect_ratio = spacing_ζ / spacing_θ
    @info "Average grid spacing [m]: dθ=$(round(spacing_θ, digits=4)), dζ=$(round(spacing_ζ, digits=4)), aspect ratio=$(round(aspect_ratio, digits=2))"
    aspect_ratio > 10.0 && @warn "Grid aspect ratio is highly anisotropic, which may degrade quadrature accuracy"

    return PlasmaGeometry3D(
        mtheta,
        nzeta,
        r,
        dr_dθ,
        dr_dζ,
        normal,
        normal_orient
    )
end

"""
    WallGeometry(inputs::VacuumInput, plasma_surf::PlasmaGeometry, wall_settings::WallShapeSettings) -> WallGeometry

Constructor to initialize the wall geometry based on the provided vacuum inputs and wall shape settings.

This performs functionality similar to portions of the `arrays` function in the original
Fortran VACUUM code. It returns a `WallGeometry` struct containing the necessary wall
surface data for vacuum calculations.

# Arguments

  - `inputs::VacuumInput`: Struct containing vacuum calculation parameters
  - `plasma_surf::PlasmaGeometry`: Struct with plasma surface geometry (used for reference)
  - `wall_settings::WallShapeSettings`: Struct specifying wall shape and parameters

# Returns

  - `WallGeometry`: Struct containing wall surface coordinates and derivatives

# Notes

  - Supports multiple wall shapes: nowall, conformal, elliptical, dee, mod_dee, from_file
  - Optionally redistributes wall points to equal arc length spacing if `equal_arc_wall=true`
"""
function WallGeometry(inputs::VacuumInput, plasma_surf::PlasmaGeometry, wall_settings::WallShapeSettings)

    # Output wall coordinate arrays
    mtheta = inputs.mtheta
    x_wall = zeros(mtheta)
    z_wall = zeros(mtheta)

    if wall_settings.shape == "nowall"
        return WallGeometry(
            true,
            x_wall,
            z_wall
        )
    end

    # Compute plasma surface quantities
    x_plasma = plasma_surf.x
    z_plasma = plasma_surf.z

    # Common geometric parameters
    xmin = minimum(x_plasma)
    xmax = maximum(x_plasma)
    zmin = minimum(z_plasma)
    zmax = maximum(z_plasma)

    r_minor = 0.5 * (xmax - xmin)
    r_major = 0.5 * (xmax + xmin)

    # Destructuring settings for readability
    (; aw, bw, cw, dw, tw, a) = wall_settings
    wcentr = 0.0 # Initialize

    if wall_settings.shape == "conformal"
        dx = a * r_minor
        @info "Calculating conformal wall shape $((@sprintf "%.2e" dx)) m from plasma surface."
        wcentr = r_major
        centerstack_min = min(0.1, 0.1 * minimum(x_plasma))  # Avoid wall crossing R=0 axis
        for i in 1:mtheta
            j = mod1(i - 1, mtheta)
            k = mod1(i + 1, mtheta)
            # Normal vector calculation
            alph = atan(x_plasma[k] - x_plasma[j], z_plasma[j] - z_plasma[k])
            x_wall[i] = max(centerstack_min, x_plasma[i] + a * r_minor * cos(alph))
            z_wall[i] = z_plasma[i] + a * r_minor * sin(alph)
        end

        if any(x_wall .<= centerstack_min + eps(Float64))
            @warn "Conformal wall with a=$a would cross R=0 axis; forcing minimum wall R to $(@sprintf "%.2e" centerstack_min) m to avoid unphysical geometry."
        end

    elseif wall_settings.shape == "elliptical"
        @info "Calculating elliptical wall shape with a = $((@sprintf "%.2e" a)) m."
        wcentr = r_major

        zrad = 0.5 * (zmax - zmin)
        zh = sqrt(abs(zrad^2 - r_minor^2))
        zmuw = log((a/zh) + sqrt((a/zh)^2 + 1))
        bw_eff = (zh * cosh(zmuw)) / a

        for i in 1:mtheta
            the = (i - 1) * (2π / mtheta)
            x_wall[i] = r_major + a * cos(the)
            z_wall[i] = -bw_eff * a * sin(the)
        end

    elseif wall_settings.shape == "dee"
        wcentr = r_major + cw * r_minor
        @info "Calculating dee-shaped wall with R = $((@sprintf "%.2e" wcentr)) + $((@sprintf "%.2e" r_minor)) * (1.0 + $((@sprintf "%.2e" a)) - $((@sprintf "%.2e" cw))) * cos(θ + $((@sprintf "%.2e" dw)) * sin(θ)), Z = -$((@sprintf "%.2e" bw)) * $((@sprintf "%.2e" r_minor)) * (1.0 + $((@sprintf "%.2e" a)) - $((@sprintf "%.2e" cw))) * sin(θ + $((@sprintf "%.2e" tw)) * sin(2θ)) - $((@sprintf "%.2e" aw)) * $((@sprintf "%.2e" r_minor)) * sin(2θ)."
        for i in 1:mtheta
            the = (i - 1) * (2π / mtheta)
            x_wall[i] = wcentr + r_minor * (1.0 + a - cw) * cos(the + dw * sin(the))
            z_wall[i] = -bw * r_minor * (1.0 + a - cw) * sin(the + tw * sin(2.0*the)) - aw * r_minor * sin(2.0*the)
        end

    elseif wall_settings.shape == "mod_dee"
        @info "Calculating modified dee-shaped wall with R = $((@sprintf "%.2e" cw)) + $((@sprintf "%.2e" a)) * cos(θ + $((@sprintf "%.2e" dw)) * sin(θ)), Z = -$((@sprintf "%.2e" bw)) * $((@sprintf "%.2e" a)) * sin(θ + $((@sprintf "%.2e" tw)) * sin(2θ)) - $((@sprintf "%.2e" aw)) * sin(2θ)."
        wcentr = cw
        for i in 1:mtheta
            the = (i - 1) * (2π / mtheta)
            x_wall[i] = cw + a * cos(the + dw * sin(the))
            z_wall[i] = -bw * a * sin(the + tw * sin(2.0*the)) - aw * sin(2.0*the)
        end

    else
        filepath = wall_settings.shape
        if !isfile(filepath)
            error(
                "Wall geometry file $filepath does not exist. " *
                "Please set the wall shape parameter to a valid file path or a built-in shape " *
                "(nowall, conformal, elliptical, dee, mod_dee)."
            )
        end

        wcentr = 0.0
        open(wall_settings.shape, "r") do io
            npots0 = parse(Int, readline(io))  # Number of points in file
            wcentr = parse(Float64, readline(io))
            readline(io) # Skip header/comment line

            npots0 < mtheta && error("Wall geometry file $filepath contains fewer points ($npots0) than mtheta ($mtheta).")

            for i in 1:mtheta
                line = split(readline(io))
                # Assumes file format: [index  R_coord  Z_coord]
                x_wall[i] = parse(Float64, line[2])
                z_wall[i] = parse(Float64, line[3])
            end
        end
    end

    # Optional: Re-parameterization for equal arc length spacing of wall points
    if wall_settings.equal_arc_wall
        @info "Re-distributing wall points to equal arc length spacing (assumes closed, toroidal wall)."
        x_wall, z_wall = distribute_to_equal_arc_grid(x_wall, z_wall)
    end

    # To add support for x<0 walls, be sure to carefully replicate Chance's fortran code x<0 handling in the kernel function to account for the additional singularities associated with this
    any(x_wall .<= 0.0) && error("Wall R-coordinates contain non-physical values (R <= 0). Check wall geometry.")

    return WallGeometry(false, x_wall, z_wall)
end

"""
    WallGeometry3D

Struct holding wall geometry data for vacuum calculations. Arrays have `mtheta * nzeta` rows,
ordered with the poloidal index fastest.

# Fields

  - `nowall::Bool`: Boolean flag indicating if there is no wall
  - `is_closed_toroidal::Bool`: Boolean flag indicating if the wall is a closed toroidal surface
  - `mtheta::Int`: Number of poloidal grid points
  - `nzeta::Int`: Number of toroidal grid points
  - `r::Matrix{Float64}`: (x, y, z) wall coordinates at each grid point
  - `dr_dθ::Matrix{Float64}`: Derivative dR/dθ at wall
  - `dr_dζ::Matrix{Float64}`: Derivative dR/dζ at wall
  - `normal::Matrix{Float64}`: Outward normal vectors at wall
"""
struct WallGeometry3D
    nowall::Bool
    is_closed_toroidal::Bool
    mtheta::Int
    nzeta::Int
    r::Matrix{Float64}
    dr_dθ::Matrix{Float64}
    dr_dζ::Matrix{Float64}
    normal::Matrix{Float64}
    normal_orient::Int
end

"""
    WallGeometry3D(inputs::VacuumInput, plasma_surf::PlasmaGeometry3D, wall_settings::WallShapeSettings) -> WallGeometry3D

Constructor to initialize the 3D wall geometry based on the provided vacuum inputs, plasma surface and
wall shape settings. This is the 3D counterpart of [`WallGeometry`](@ref) and selects the shape the same
way: an axisymmetric boundary builds the 2D poloidal contour and revolves it, so every shape
[`WallGeometry`](@ref) offers is available; a non-axisymmetric boundary offsets the plasma surface.

Expects a full-torus boundary — call [`expand_field_periods`](@ref) first when `nfp > 1`.

# Arguments

  - `inputs::VacuumInput`: Struct containing vacuum calculation parameters
  - `plasma_surf::PlasmaGeometry3D`: Plasma surface the wall is built around (used by the conformal wall)
  - `wall_settings::WallShapeSettings`: Struct specifying wall shape and parameters

# Returns

  - `WallGeometry3D`: Struct containing wall surface coordinates and derivatives

# Notes

  - A non-axisymmetric boundary supports only nowall and conformal
  - The conformal wall for a non-axisymmetric boundary displaces each plasma point along its own normal,
    which keeps wall grid index `(i, j)` the closest wall point to plasma index `(i, j)` — the
    correspondence the near-field patch of `compute_3D_kernel_matrices!` assumes
  - Rejects a conformal offset that folds the surface, and warns when the plasma–wall gap is smaller
    than one cell of the coarser grid (the double-layer near-field quadrature cannot resolve it)
"""
function WallGeometry3D(inputs::VacuumInput, plasma_surf::PlasmaGeometry3D, wall_settings::WallShapeSettings)

    # Basic wall flags
    nowall = wall_settings.shape == "nowall"
    is_closed_toroidal = true

    (; mtheta, nzeta) = inputs
    dθ = 2π / mtheta
    dζ = 2π / nzeta
    θ_grid = range(; start=0, length=mtheta, step=dθ)
    ϕ_grid = range(; start=0, length=nzeta, step=dζ)
    num_points = mtheta * nzeta

    # Output wall coordinate arrays
    r = zeros(num_points, 3)
    normal = zeros(num_points, 3)
    dr_dθ = zeros(num_points, 3)
    dr_dζ = zeros(num_points, 3)
    normal_orient = 1

    if nowall
        @info "Using no wall"
        return WallGeometry3D(
            nowall,
            is_closed_toroidal,
            mtheta,
            nzeta,
            r,
            dr_dθ,
            dr_dζ,
            normal,
            normal_orient
        )
    end

    # expand_field_periods leaves an axisymmetric boundary alone, so nfp > 1 can only arrive here with
    # per-period counts that the rest of the 3D solve reads as full-torus ones.
    inputs.nfp > 1 && error("3D wall geometry requires a full-torus boundary. Call expand_field_periods(inputs) first, or supply the whole torus with nfp = 1.")

    if inputs.nzeta_in == 1
        # Axisymmetric boundary: build the 2D poloidal contour and revolve it toroidally
        surf_2D = PlasmaGeometry(inputs)
        wall_2D = WallGeometry(inputs, surf_2D, wall_settings)
        for i in 1:mtheta, (j, ϕ) in enumerate(ϕ_grid)
            r[i+mtheta*(j-1), :] .= [wall_2D.x[i] * cos(ϕ), wall_2D.x[i] * sin(ϕ), wall_2D.z[i]]
        end
    elseif wall_settings.shape == "conformal"
        # Displace every plasma point outward along its own normal
        wall_settings.equal_arc_wall && @warn "equal_arc_wall is ignored for non-axisymmetric (nzeta_in > 1) walls: it re-parameterizes a 2D contour and would break the plasma/wall index alignment the near-field patch relies on."

        # Gap scales with the plasma's radial extent, as in the 2D conformal wall
        R_plasma = [hypot(plasma_surf.r[idx, 1], plasma_surf.r[idx, 2]) for idx in axes(plasma_surf.r, 1)]
        offset_gap = wall_settings.a * 0.5 * (maximum(R_plasma) - minimum(R_plasma))
        @info "Calculating conformal wall shape $((@sprintf "%.2e" offset_gap)) m from plasma surface."

        # Plasma normal points into the plasma, so the displacement is along -normal
        @inbounds for idx in axes(plasma_surf.r, 1)
            scale = -offset_gap / sqrt(plasma_surf.normal[idx, 1]^2 + plasma_surf.normal[idx, 2]^2 + plasma_surf.normal[idx, 3]^2)
            for k in 1:3
                r[idx, k] = plasma_surf.r[idx, k] + scale * plasma_surf.normal[idx, k]
            end
        end
    else
        error("Wall shape $(wall_settings.shape) is not available for a non-axisymmetric boundary (nzeta_in > 1).")
    end

    # Compute tangent vectors and normal vectors via periodic bicubic splines
    itps = [cubic_interp((θ_grid, ϕ_grid), reshape(r[:, k], mtheta, nzeta); bc=(PeriodicBC(; endpoint=:exclusive), PeriodicBC(; endpoint=:exclusive))) for k in 1:3]
    for i in 1:mtheta, j in 1:nzeta
        idx = i + (j - 1) * mtheta
        for k in 1:3
            partials = itps[k].nodal_derivs.partials
            dr_dθ[idx, k] = partials[2, i, j]
            dr_dζ[idx, k] = partials[3, i, j]
        end
        cross3!(normal, dr_dθ, dr_dζ, idx)
    end

    # Determine normal orientation (outward for wall) and enforce it
    idx = argmax(view(r, :, 1)) # outboard midplane
    normal_orient = normal[idx, 1] > 0 ? 1 : -1
    @views normal .*= normal_orient

    # Same-index plasma–wall separation: the near-field patch is centred on this pair.
    gap = minimum(hypot(r[idx, 1] - plasma_surf.r[idx, 1], r[idx, 2] - plasma_surf.r[idx, 2], r[idx, 3] - plasma_surf.r[idx, 3]) for idx in axes(r, 1))

    # Fold check needs a pointwise normal offset (same-index pair) - equal_arc_wall re-parameterizes and breaks that pairing
    if wall_settings.shape == "conformal" && (inputs.nzeta_in > 1 || !wall_settings.equal_arc_wall)
        # The offset stays regular while the normals stay aligned and the area element has not collapsed; both fail past the local concave radius of curvature
        min_align = Inf # min n̂_wall · n̂_plasma_outward; +1 healthy, ≤0 folded
        min_area_ratio = Inf # min ||n_wall||/||n_plasma||; →0 at a caustic
        @inbounds for idx in axes(normal, 1)
            norm_wall = sqrt(normal[idx, 1]^2 + normal[idx, 2]^2 + normal[idx, 3]^2)
            norm_plasma = sqrt(plasma_surf.normal[idx, 1]^2 + plasma_surf.normal[idx, 2]^2 + plasma_surf.normal[idx, 3]^2)
            # Plasma n in, wall n out of vacuum → healthy offset dots to −1; store −cosine so +1 is aligned.
            dot_wp = normal[idx, 1] * plasma_surf.normal[idx, 1] + normal[idx, 2] * plasma_surf.normal[idx, 2] + normal[idx, 3] * plasma_surf.normal[idx, 3]
            min_align = min(min_align, -dot_wp / (norm_wall * norm_plasma))
            min_area_ratio = min(min_area_ratio, norm_wall / norm_plasma)
        end

        min_align <= 0.0 && error(
            "Conformal wall offset of $((@sprintf "%.2e" gap)) m self-intersects: it exceeds the local concave radius " *
            "of curvature of the plasma surface somewhere, folding the offset surface. Reduce the wall distance a."
        )
        (min_align < 0.5 || min_area_ratio < 0.5) &&
            @warn "Conformal wall is close to folding: min(n̂_wall·n̂_plasma)=$((@sprintf "%.3f" min_align)), min area-element ratio=$((@sprintf "%.3f" min_area_ratio)). Reduce the wall distance a."
    end

    # The 3D singular quadrature resolves the double-layer kernel well only while the plasma-wall gap spans a grid cell or more
    h_θ = max(sqrt(sum(abs2, dr_dθ) / num_points), sqrt(sum(abs2, plasma_surf.dr_dθ) / num_points)) * dθ
    h_ζ = max(sqrt(sum(abs2, dr_dζ) / num_points), sqrt(sum(abs2, plasma_surf.dr_dζ) / num_points)) * dζ
    cells = gap / max(h_θ, h_ζ)
    if cells < 1.0
        @warn "Plasma–wall gap $((@sprintf "%.2e" gap)) m spans only $((@sprintf "%.2f" cells)) cells of the coarser grid " *
                "(h_θ=$((@sprintf "%.2e" h_θ)) m, h_ζ=$((@sprintf "%.2e" h_ζ)) m). The double-layer near-field quadrature is inaccurate " *
                "below one cell. Refine the coarser of mtheta/nzeta, or move the wall out."
    end

    return WallGeometry3D(
        nowall,
        is_closed_toroidal,
        mtheta,
        nzeta,
        r,
        dr_dθ,
        dr_dζ,
        normal,
        normal_orient
    )
end
