[EQUIL_CONTROL]
eq_type = "efit"  # Type of the input 2D equilibrium file
eq_filename = "g147131.02300_DIIID_KEFIT"

jac_type = "hamada"  # Working coordinate system for DCON and GPEC
power_bp = 0
power_b = 0
power_r = 0

grid_type = "ldp"  # Radial grid packing strategy
psilow = 1e-4
psihigh = 0.993
mpsi = 128
mtheta = 256
newq0 = 0
use_classic_splines = false
input_only = false

[EQUIL_OUTPUT]
gse_flag = false
out_eq_1d = false
bin_eq_1d = false
out_eq_2d = false
bin_eq_2d = true
out_2d = false
bin_2d = false
dump_flag = false
